### ISSUE TITLE
Bad performance when editing big json files

### ISSUE THREAD

**Issue by UlyssesWu** [zetoken/JSon-Editor#5]
I'm trying to edit a 5MB json file and the program costs about 500MB RAM, twice as the Json Viewer by Eyal Post. And the program became very slow...

![bad-performance-json-editor](https://cloud.githubusercontent.com/assets/4312781/24070633/49e88048-0bfc-11e7-9fc2-128ce3832f47.png)

**Comment by zetoken** [comment]
Hi,
It's a problem I know with large json files. I will work on this issue in my (rare) spare time.

**Comment by zetoken** [comment]
After a quick profiling and some tests with a 35Mo json file, the main memory eater is the json text written in each nodes and subnodes.
2 things to be implemented soon:
- Dynamic load of subnodes (all nodes are loaded at once for now)
- Label length limit

**Comment by UlyssesWu** [comment]
> my (rare) spare time

I understand... I don't have much spare time either and always be asked like this... 😭

**Comment by zetoken** [comment]
It was finally easier than I thought because the mechanisms needed to improve the memory cost were already ready for a long time :-) .
Some key figures after the improvement (memory as shown in task explorer):
**Using a 537 Ko json file, 19677 lines**
Memory used between 26Mo and 35Mo depending on garbage collector will (down from 160Mo).
**Using a 6Mo json file, 160897 lines**
Memory used between 85Mo and 100Mo depending on garbage collector will.
**Using a 35Mo json file, 790920 lines**
Memory used between 430Mo and 600Mo depending on garbage collector will (down from 2.2Go...).

I think another improvement will be needed when using "Expand All" on root node of a large file as it may take a (very) long time.

@UlyssesWu Could you please test the last build and report any performance issue ?

**Comment by UlyssesWu** [comment]
@zetoken I‘ve tried the latest build and yes, it usually costs less than 100MB RAM on my 2MB~8MB json files. That's very impressive. The only issue I faced, as you have said, is that I will definitely get a `OutOfMemory exception` when I use Expand All on root node (from a 2.3MB file and larger). But at least I don't think I will use that function. **Thanks for the quick fix!**

BTW, the link "Download last build from appveyor." in `readme.md` doesn't work for me. The "build passing" sticker works.

**Comment by zetoken** [comment]
Thanks for the reply.
I'll keep this issue opened until I fix the Expand All issue.

**Comment by zetoken** [comment]
The `OutOfMemoryException` when trying to expand all nodes on a large json file is really touchy. I'd better close this issue (memory performance) and open a new one (see #7).
